package schoolFestival.domain.model;

import java.io.Serializable;

/**
 * 値引き対象商品 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductDiscountEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品. */
	private ProductEntity product;

	/** 値引き. */
	private DiscountEntity discount;

	/**
	 * コンストラクタ.
	 */
	public ProductDiscountEntity() {
	}

	/**
	 * 商品 を設定します.
	 * 
	 * @param product
	 *            商品
	 */
	public void setProduct(ProductEntity product) {
		this.product = product;
	}

	/**
	 * 商品 を取得します.
	 * 
	 * @return 商品
	 */
	public ProductEntity getProduct() {
		return this.product;
	}

	/**
	 * 値引き を設定します.
	 * 
	 * @param discount
	 *            値引き
	 */
	public void setDiscount(DiscountEntity discount) {
		this.discount = discount;
	}

	/**
	 * 値引き を取得します.
	 * 
	 * @return 値引き
	 */
	public DiscountEntity getDiscount() {
		return this.discount;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((product == null) ? 0 : product.hashCode());
		result = prime * result + ((discount == null) ? 0 : discount.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductDiscountEntity other = (ProductDiscountEntity) obj;
		if (product == null) {
			if (other.product != null) {
				return false;
			}
		} else if (!product.equals(other.product)) {
			return false;
		}
		if (discount == null) {
			if (other.discount != null) {
				return false;
			}
		} else if (!discount.equals(other.discount)) {
			return false;
		}
		return true;
	}

}
