package schoolFestival.domain.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 商品価格 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="PRODUCT_PRICE")
public class ProductPriceEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品価格ID. */
	@Id
	private Integer id;

	/** 商品. */
	private ProductEntity product;

	/** 価格. */
	private Integer price;

	/** 適用開始日時. */
	private Date startDatetime;

	/** 適用終了日時. */
	private Date endDatetime;

	/** 売上明細 一覧. */
	private Set<SalesDetailEntity> salesDetailSet;

	/**
	 * コンストラクタ.
	 */
	public ProductPriceEntity() {
		this.salesDetailSet = new HashSet<SalesDetailEntity>();
	}

	/**
	 * 商品価格ID を設定します.
	 * 
	 * @param id
	 *            商品価格ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 商品価格ID を取得します.
	 * 
	 * @return 商品価格ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 商品 を設定します.
	 * 
	 * @param product
	 *            商品
	 */
	public void setProduct(ProductEntity product) {
		this.product = product;
	}

	/**
	 * 商品 を取得します.
	 * 
	 * @return 商品
	 */
	public ProductEntity getProduct() {
		return this.product;
	}

	/**
	 * 価格 を設定します.
	 * 
	 * @param price
	 *            価格
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * 価格 を取得します.
	 * 
	 * @return 価格
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * 適用開始日時 を設定します.
	 * 
	 * @param startDatetime
	 *            適用開始日時
	 */
	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	/**
	 * 適用開始日時 を取得します.
	 * 
	 * @return 適用開始日時
	 */
	public Date getStartDatetime() {
		return this.startDatetime;
	}

	/**
	 * 適用終了日時 を設定します.
	 * 
	 * @param endDatetime
	 *            適用終了日時
	 */
	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	/**
	 * 適用終了日時 を取得します.
	 * 
	 * @return 適用終了日時
	 */
	public Date getEndDatetime() {
		return this.endDatetime;
	}

	/**
	 * 売上明細 一覧を設定します.
	 * 
	 * @param salesDetailSet
	 *            売上明細 一覧
	 */
	public void setSalesDetailSet(Set<SalesDetailEntity> salesDetailSet) {
		this.salesDetailSet = salesDetailSet;
	}

	/**
	 * 売上明細 を追加します.
	 * 
	 * @param salesDetail
	 *            売上明細
	 */
	public void addSalesDetail(SalesDetailEntity salesDetail) {
		this.salesDetailSet.add(salesDetail);
	}

	/**
	 * 売上明細 一覧を取得します.
	 * 
	 * @return 売上明細 一覧
	 */
	public Set<SalesDetailEntity> getSalesDetailSet() {
		return this.salesDetailSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductPriceEntity other = (ProductPriceEntity) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
