package schoolFestival.domain.model;

import java.io.Serializable;

/**
 * 売上明細 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SalesDetailEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 売上. */
	private SalesEntity sales;

	/** 商品価格. */
	private ProductPriceEntity productProductPrice;

	/** 個数. */
	private Integer qty;

	/**
	 * コンストラクタ.
	 */
	public SalesDetailEntity() {
	}

	/**
	 * 売上 を設定します.
	 * 
	 * @param sales
	 *            売上
	 */
	public void setSales(SalesEntity sales) {
		this.sales = sales;
	}

	/**
	 * 売上 を取得します.
	 * 
	 * @return 売上
	 */
	public SalesEntity getSales() {
		return this.sales;
	}

	/**
	 * 商品価格 を設定します.
	 * 
	 * @param productProductPrice
	 *            商品価格
	 */
	public void setProductProductPrice(ProductPriceEntity productProductPrice) {
		this.productProductPrice = productProductPrice;
	}

	/**
	 * 商品価格 を取得します.
	 * 
	 * @return 商品価格
	 */
	public ProductPriceEntity getProductProductPrice() {
		return this.productProductPrice;
	}

	/**
	 * 個数 を設定します.
	 * 
	 * @param qty
	 *            個数
	 */
	public void setQty(Integer qty) {
		this.qty = qty;
	}

	/**
	 * 個数 を取得します.
	 * 
	 * @return 個数
	 */
	public Integer getQty() {
		return this.qty;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sales == null) ? 0 : sales.hashCode());
		result = prime * result + ((productProductPrice == null) ? 0 : productProductPrice.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SalesDetailEntity other = (SalesDetailEntity) obj;
		if (sales == null) {
			if (other.sales != null) {
				return false;
			}
		} else if (!sales.equals(other.sales)) {
			return false;
		}
		if (productProductPrice == null) {
			if (other.productProductPrice != null) {
				return false;
			}
		} else if (!productProductPrice.equals(other.productProductPrice)) {
			return false;
		}
		return true;
	}

}
