package schoolFestival.domain.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 売上 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name="SALES")
public class SalesEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 売上ID. */
	@Id
	private Integer id;

	/** 売上日時. */
	private Date datetime;

	/** 値引きID. */
	private Integer discountId;

	/** 売上明細 一覧. */
	private Set<SalesDetailEntity> salesDetailSet;

	/**
	 * コンストラクタ.
	 */
	public SalesEntity() {
		this.salesDetailSet = new HashSet<SalesDetailEntity>();
	}

	/**
	 * 売上ID を設定します.
	 * 
	 * @param id
	 *            売上ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 売上ID を取得します.
	 * 
	 * @return 売上ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 売上日時 を設定します.
	 * 
	 * @param datetime
	 *            売上日時
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	/**
	 * 売上日時 を取得します.
	 * 
	 * @return 売上日時
	 */
	public Date getDatetime() {
		return this.datetime;
	}

	/**
	 * 値引きID を設定します.
	 * 
	 * @param discountId
	 *            値引きID
	 */
	public void setDiscountId(Integer discountId) {
		this.discountId = discountId;
	}

	/**
	 * 値引きID を取得します.
	 * 
	 * @return 値引きID
	 */
	public Integer getDiscountId() {
		return this.discountId;
	}

	/**
	 * 売上明細 一覧を設定します.
	 * 
	 * @param salesDetailSet
	 *            売上明細 一覧
	 */
	public void setSalesDetailSet(Set<SalesDetailEntity> salesDetailSet) {
		this.salesDetailSet = salesDetailSet;
	}

	/**
	 * 売上明細 を追加します.
	 * 
	 * @param salesDetail
	 *            売上明細
	 */
	public void addSalesDetail(SalesDetailEntity salesDetail) {
		this.salesDetailSet.add(salesDetail);
	}

	/**
	 * 売上明細 一覧を取得します.
	 * 
	 * @return 売上明細 一覧
	 */
	public Set<SalesDetailEntity> getSalesDetailSet() {
		return this.salesDetailSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SalesEntity other = (SalesEntity) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
