package schoolFestival.domain.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 当番 モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ShiftEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 当番ID. */
	private Integer id;

	/** 学生. */
	private StudentEntity student;

	/** 開始日時. */
	private Date startDatetime;

	/** 終了日時. */
	private Date endDatetime;

	/**
	 * コンストラクタ.
	 */
	public ShiftEntity() {
	}

	/**
	 * 当番ID を設定します.
	 * 
	 * @param id
	 *            当番ID
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 当番ID を取得します.
	 * 
	 * @return 当番ID
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 学生 を設定します.
	 * 
	 * @param student
	 *            学生
	 */
	public void setStudent(StudentEntity student) {
		this.student = student;
	}

	/**
	 * 学生 を取得します.
	 * 
	 * @return 学生
	 */
	public StudentEntity getStudent() {
		return this.student;
	}

	/**
	 * 開始日時 を設定します.
	 * 
	 * @param startDatetime
	 *            開始日時
	 */
	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	/**
	 * 開始日時 を取得します.
	 * 
	 * @return 開始日時
	 */
	public Date getStartDatetime() {
		return this.startDatetime;
	}

	/**
	 * 終了日時 を設定します.
	 * 
	 * @param endDatetime
	 *            終了日時
	 */
	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	/**
	 * 終了日時 を取得します.
	 * 
	 * @return 終了日時
	 */
	public Date getEndDatetime() {
		return this.endDatetime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ShiftEntity other = (ShiftEntity) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
